name: testingheartrate
description: "A new Flutter project."

publish_to: 'none'

version: 8.0.0+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.1
  video_player: ^2.5.0
  audioplayers: ^6.4.0
  audio_session: ^0.1.24
  shared_preferences: ^2.5.2
  socket_io_client: ^3.0.2
  sign_in_with_apple: ^6.1.4
  flutter_svg: ^2.0.0
  flutter_riverpod: ^2.6.1
  audio_service: ^0.18.0
  just_audio: ^0.9.5
  confetti: ^0.7.0
  pie_chart: ^5.4.0
  fl_chart: ^0.69.0
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  app_links: ^6.4.0
  wakelock_plus: ^1.3.2
  just_audio_cache: ^0.1.2
  just_audio_background: ^0.0.1-beta.17
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.1.1
  screen_brightness: ^2.1.4
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  pedometer_2: ^5.0.4
  cm_pedometer: ^1.2.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.1  
  sensors_plus: ^3.0.2
  firebase_messaging: ^15.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/audio/
    - assets/audio/aradium/overlay/0/
    - assets/audio/aradium/overlay/1/
    - assets/audio/aradium/overlay/2/
    - assets/audio/aradium/overlay/3/
    - assets/audio/aradium/overlay/4/
    - assets/audio/aradium/overlay/5/
    - assets/audio/aradium/overlay/6/
    - assets/audio/aradium/overlay/7/
    - assets/audio/aradium/overlay/8/
    - assets/audio/aradium/overlay/9/
    - assets/audio/aradium/overlay/10/
    - assets/audio/aradium/overlay/11/
    - assets/audio/aradium/overlay/12/
    - assets/audio/aradium/overlay/13/
    - assets/audio/aradium/overlay/14/
    - assets/audio/aradium/overlay/15/
    - assets/audio/aradium/overlay/16/
    - assets/audio/aradium/overlay/17/
    - assets/audio/luther/overlay/0/
    - assets/audio/luther/overlay/1/
    - assets/audio/luther/overlay/2/
    - assets/audio/luther/overlay/3/
    - assets/audio/luther/overlay/4/
    - assets/audio/luther/overlay/5/
    - assets/audio/luther/overlay/6/
    - assets/audio/luther/overlay/7/
    - assets/audio/luther/overlay/8/
    - assets/audio/luther/overlay/9/
    - assets/audio/luther/overlay/10/
    - assets/audio/luther/overlay/11/
    - assets/audio/luther/overlay/12/
    - assets/audio/luther/overlay/13/
    - assets/audio/luther/overlay/14/
    - assets/audio/luther/overlay/15/
    - assets/audio/luther/overlay/16/
    - assets/audio/luther/overlay/17/
    - assets/audio/smm/overlay/0/
    - assets/audio/pacing/
    - assets/audio/stop/
    - assets/audio/smm/
    - assets/audio/aradium/
    - assets/audio/luther/
    - assets/audio/detour/
    - assets/audio/smm/detour/0/
    - assets/audio/smm/detour/1/
    - assets/audio/smm/detour/2/
    - assets/audio/smm/detour/3/
    - assets/audio/smm/detour/4/
    - assets/audio/smm/detour/5/
    - assets/audio/smm/detour/6/
    - assets/audio/smm/detour/7/
    - assets/audio/smm/detour/8/
    - assets/audio/smm/detour/9/
    - assets/audio/smm/detour/10/
    - assets/audio/smm/detour/11/
    - shorebird.yaml
  fonts:
    - family: Thewitcher
      fonts:
        - asset: assets/fonts/Thewitcher.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang.ttf